### PR TITLE
removing reactions feature

### PR DESCRIPTION
**Pull request by Zamiell**
when reading messages in the Discord server, it is common that robo baby will react to a message.
however, because you can't tell who a reaction is from, you have to mouse over the reaction *every single time* to see whether or not it is from a real person or from the bot.
thus, this is a huge time-waster.

furthermore, the reactions are not relevant to any conversation, since they are generated randomly.
reactions that don't apply to the situation are both confusing and annoying.

so please, let's remove this feature forever.
it is negative value to the server.

### CODE REVIEW

**Comment by ryderhicks** [comment]
I would very much disagree: the reactions are rare, and I believe add fun and flavor. If you can find majority agreement in #meta then I will merge.

**Comment by Zamiell** [comment]
how about as a compromise, we compile a channel whitelist of only non-serious channels, such as:

```ts
const CHANNEL_WHITELIST = [
  "#basement",
  "#robochat",
  ...etc
];
```

and then restrict the reacting to these subset of channels

**Comment by ryderhicks** [comment]
I think it would be fair to remove it, as well as text responses, from the modding category. We can use a new env var `CATEGORY_MODDING` and check it against the channel's parentId.

**Comment by Zamiell** [comment]
great, thank you!
i'll close the PR now then and let you handle that

**Pull request closed without merging**
